const questions = {
  categories: ['Locations', 'Josh Songs', 'Work History', 'Bad Decisions', 'Names', 'Sports of the Josh',
                'The year 1987', 'On May 24th', 'Anagrams', 'Famous Josh\'s', 'Foods of the Josh', 'Josh Photos'],

  Locations: [{v: 200, q: 'Josh\'s first city after High School', a: 'Christchurch', f:''},{v: 400, q: 'Location of Josh\'s Conception', a: 'Palmerston North (probably)', f:''},{v: 600, q: 'Where all the important people saw Sea Turtles', a: 'Honolulu, Hawaii', f:''},{v: 800, q: 'West Coast City, Holiday with the Skiba\'s, mainly prisons and Sea Lions', a: 'San Francisco', f:''},{v: 1000, q: 'Connie\s Destination', a: 'Dunedin', f:''}],
  JoshSongs: [{v: 200, q: 'Song and Artist', a: 'Smashing Pumpkins, Mellon Collie and the Infinite Sadness', f:'src/assets/audio/mellon.mp3'},{v: 400, q: 'Song and Artist', a: 'Sport and Religion, Shihad', f:'src/assets/audio/sport.mp3'},{v: 600, q: 'Song and Artist', a: 'Wish You Were Here, Incubus', f:'src/assets/audio/wish.mp3'},{v: 800, q: 'Song and Artist', a: 'With or Without You, U2. Top of the Billboard Charts May 24 1987', f:'src/assets/audio/preferablywithout.mp3'},{v: 1000, q: 'Song and Artist. Adam\'s Josh Song', a: 'Electric Dreams, Shapeshifter', f:'src/assets/audio/shape.mp3'}],
  WorkHistory: [{v: 200, q: 'First Job', a: 'Cherrywood 4 Square', f:''},{v: 400, q: 'The Fast Food Chain', a: 'KFC', f:''},{v: 600, q: 'Volunteering with which animals at the SPCA', a: 'Dogs', f:''},{v: 800, q: 'The company with the Platinum Amex cards', a: 'Hewlett Packard', f:''},{v: 1000, q: 'Josh always wanted to be an...', a: 'Engineer', f:''}],
  BadDecisions: [{v: 200, q: 'Location of Josh\s biggest scar', a: 'Knee', f:''},{v: 400, q: 'True or False: Josh has eaten a piece of a dog biscuit', a: 'True, Adam was there', f:''},{v: 600, q: 'Possibly dating someone from this city at the bottom of New Zealand', a: 'Invercargill', f:''},{v: 800, q: 'The reason for Josh\s biggest scar', a: 'Practising for School Olympics', f:''},{v: 1000, q: 'Trying to purchase WHAT and find a decent WHAT was a bad decision in Vancouver', a: 'Timberlands boots and a haircut', f:''}],
  Names: [{v: 200, q: 'First Girlfriend', a: 'Charlotte', f:''},{v: 400, q: 'Name of Josh\'s Daughter\'s School (2018)', a: 'Dr Phillips Elementary', f:''},{v: 600, q: 'Josh\'s Daughter\'s Best Friends\'s Name', a: 'ASK', f:''},{v: 800, q: 'Name of that beautiful, reliable, nice smelling, clean, silver Holden Commodore', a: 'Wes', f:''},{v: 1000, q: 'Josh\'s Godfather', a: 'Stefan Fletcher', f:'../src/assets/images/stefan.JPG'}],
  SportsoftheJosh: [{v: 200, q: 'The city of "that" Cricket World Cup Semi Final', a: 'Wellington', f:''},{v: 400, q: 'The first brother to play Hockey', a: 'Adam', f:''},{v: 600, q: 'Name 1 character from Pulp Sport', a: 'The Mascot, The Mad Mad Butcher, Steve Urban, Bill and Ben, etc.', f:''},{v: 800, q: 'Josh\'s Number 1 Super Rugby Team', a: 'Crusaders (according to Facebook)', f:''},{v: 1000, q: 'The name of the INTERVIEWER in the "Don\'t Blush Baby" incident', a: 'Mel McLaughlin', f:''}],

  Theyear1987: [{v: 400, q: 'The first edition of which sporting event', a: 'Rugby World Cup', f:''},{v: 800, q: 'Which British Leader is elected for a Third Term', a: 'Margaret Thatcher', f:''},{v: 1200, q: 'Which cartoon first appears in short previews', a: 'The Simpsons', f:''},{v: 1600, q: 'Which coffee company opens its first store outside its founding city', a: 'Starbucks', f:''},{v: 2000, q: 'Pick the lie: An American shoots himself on live TV, a Suoernova is seen with the naked eye, A McDonalds opens for the first time in China', a: 'McDonalds, but KFC does make it to China for the first time', f:''}],
  Maythe24th: [{v: 400, q: '1956, the first edition of which European Song Contest', a: 'Eurovision', f:''},{v: 800, q: '1883 Which New York Bridge opens', a: 'Brooklyn Bridge', f:''},{v: 1200, q: 'Published 1830, Who had a little what?', a: 'Mary had a little lamb', f:''},{v: 1600, q: 'Death of which \'Polish\' Astronomer in 1543', a: 'Nicolaus Copernicus', f:''},{v: 2000, q: 'Birthdate of one of the most successful ever folk musicians', a: 'Bob Dylan, born 1941', f:''}],
  Anagrams: [{v: 400, q: 'Viola I (Person)', a: 'Olivia', f:''},{v: 800, q: 'Rain Max (Work tool)', a: 'Xamarin', f:''},{v: 1200, q: 'Cramp End', a: 'Nerd Camp', f:''},{v: 1600, q: 'Levelness No Rusts (Person)', a: 'Russell Stevenson', f:''},{v: 2000, q: 'Mattress Oats', a: 'Toastmasters', f:''}],
  FamousJoshs: [{v: 400, q: 'All Blacks Flanker', a: 'Josh Kronfeld', f:''},{v: 800, q: 'U2 Album', a: 'The Joshua Tree', f:''},{v: 1200, q: 'American actor and former model', a: 'Josh Duhamel, also accept Josh Hartnett', f:''},{v: 1600, q: 'Queens of the Stone Age frontman', a: 'Josh Homme', f:''},{v: 2000, q: 'Which American writer used "Josh" as an early psuedonym of his Pen Name, hint: 10/10 moustache', a: 'Mark Twain', f:''}],
  FoodsoftheJosh: [{v: 400, q: 'Josh\'s Favourite Dessert', a: 'Lemon Meringue Pie', f:''},{v: 800, q: 'The secret ingredient in those expensive cocktails', a: 'Gunpowder', f:''},{v: 1200, q: 'Josh\'s favourite coffee is from what country (2 answers)', a: 'Vietnam or Cuba', f:''},{v: 1600, q: 'Broke one bottle of this, and received 12 replacement bottles', a: 'Jack Daniels', f:''},{v: 2000, q: 'Essential Josh Flatting Food ingredient', a: 'Frozen Vegetables aka Mixies', f:''}],
  JoshPhotos: [{v: 400, q: 'Name the City', a: 'Vancouver', f:'src/assets/images/shining.JPG'},{v: 800, q: 'Name the annual "holiday"', a: 'Father\'s Day', f:'src/assets/images/fathersday.JPG'},{v: 1200, q: 'Name the Sport where this was taken', a: 'Archery', f:'src/assets/images/archery.JPG'},{v: 1600, q: 'Name the puppet thing', a: 'Bobby (I think)', f:'src/assets/images/puppet.JPG'},{v: 2000, q: 'Name the Boat', a: 'USS Missouri', f:'src/assets/images/ship.JPG'}]

};

export default questions;

