const questions = {
  categories: ['Locations', 'Josh Songs', 'Work History', 'Bad Decisions', 'Names', 'Sports of the Josh',
                'The year 1987', 'On May 24th', 'Anagrams', 'Famous Josh\'s', 'Foods of the Josh', 'Josh Photos'],

  Locations: [{v: 200, q: 'Josh\'s first city after High School', a: 'Christchurch', f:'', c: false},
    {v: 400, q: 'Location of Josh\'s Conception \n(assumed)', a: 'Palmerston North', f:'', c: false},
    {v: 600, q: 'Where all the important \npeople saw Sea Turtles', a: 'Honolulu, Hawaii', f:'', c: false},
    {v: 800, q: 'West Coast City, Holiday with the Skiba\'s, \nmainly prisons and Sea Lions', a: 'San Francisco', f:'', c: false},
    {v: 1000, q: 'Connie\s Destination', a: 'Dunedin', f:'', c: false}],
  JoshSongs: [{v: 200, q: 'Song and Artist', a: 'Smashing Pumpkins, \nMellon Collie and the Infinite Sadness', f:'200.mp3', c: false},
    {v: 400, q: 'Song and Artist', a: 'Sport and Religion, \nShihad', f:'400.mp3', c: false},
    {v: 600, q: 'Song and Artist', a: 'Wish You Were Here, \nIncubus', f:'600.mp3', c: false},
    {v: 800, q: 'Song and Artist', a: 'With or Without You, \nU2. Top of the Billboard Charts May 24 1987', f:'800.mp3', c: false},
    {v: 1000, q: 'Song and Artist. Adam\'s Josh Song', a: 'Electric Dreams, \nShapeshifter', f:'1000.mp3', c: false}],
  WorkHistory: [{v: 200, q: 'First Job', a: 'Cherrywood 4 Square', f:'', c: false},
    {v: 400, q: 'The Fast Food Chain Job', a: 'KFC', f:'', c: false},
    {v: 600, q: 'Volunteering with which animals \nat the SPCA', a: 'Dogs', f:'', c: false},
    {v: 800, q: 'The company with the Platinum Amex cards', a: 'Hewlett Packard', f:'', c: false},
    {v: 1000, q: 'Josh always wanted to be an...', a: 'Engineer', f:'', c: false}],
  BadDecisions: [{v: 200, q: 'Location of Josh\s biggest scar', a: 'Knee', f:'', c: false},
    {v: 400, q: 'True or False: \nJosh has eaten a piece of a dog biscuit', a: 'True, Adam was there', f:'', c: false},
    {v: 600, q: 'Possible bad decision, dating someone from this \ncity at the bottom of New Zealand', a: 'Invercargill', f:'', c: false},
    {v: 800, q: 'The reason for Josh\s biggest scar', a: 'Practising for School Olympics', f:'', c: false},
    {v: 1000, q: 'Trying to purchase WHAT and find a \ndecent WHAT was a bad decision in Vancouver', a: 'Timberlands boots and a haircut', f:'', c: false}],
  Names: [{v: 200, q: 'First Girlfriend\'s Name', a: 'Charlotte', f:'', c: false},
    {v: 400, q: 'Name of Josh\'s Daughter\'s School (2018)', a: 'Dr Phillips Elementary', f:'', c: false},
    {v: 600, q: 'Josh\'s Daughter\'s \nBest Friends\'s Name', a: 'ASK', f:'', c: false},
    {v: 800, q: 'Name of that beautiful, reliable, nice smelling, \nclean, silver Holden Commodore', a: 'Wes', f:'', c: false},
    {v: 1000, q: 'Josh\'s Godfather', a: 'Stefan Fletcher', f:'stefan.JPG', c: false}],
  SportsoftheJosh: [{v: 200, q: 'The city of "that" \nCricket World Cup Semi Final', a: 'Wellington', f:'', c: false},
    {v: 400, q: 'The first brother to play Hockey', a: 'Adam, don\'t forget it', f:'', c: false},
    {v: 600, q: 'Name 1 character from Pulp Sport', a: 'The Mascot, The Mad Mad Butcher, \nSteve Urban, Bill and Ben, etc.', f:'', c: false},
    {v: 800, q: 'Josh\'s Number 1 Super Rugby Team', a: 'Crusaders (according to Facebook)', f:'', c: false},
    {v: 1000, q: 'The name of the INTERVIEWER \nin the "Don\'t Blush Baby" incident', a: 'Mel McLaughlin', f:'', c: false}],

  Theyear1987: [{v: 400, q: 'The first edition of \nwhich sporting event', a: 'Rugby World Cup', f:'', c: false},
    {v: 800, q: 'Which British Leader is \nelected for a Third Term', a: 'Margaret Thatcher', f:'', c: false},
    {v: 1200, q: 'Which cartoon first appears in short previews', a: 'The Simpsons', f:'', c: false},
    {v: 1600, q: 'Which coffee company opens its first\n store outside its founding city', a: 'Starbucks', f:'', c: false},
    {v: 2000, q: 'Pick the lie:\n An American shoots himself on live TV \nA Supernova is seen with the naked eye\nA McDonald\'s opens for the first time in China', a: 'McDonalds, but \nKFC does make it to China for the first time', f:'', c: false}],
  Maythe24th: [{v: 400, q: '1956, the first edition of \nwhich European Song Contest', a: 'Eurovision', f:'', c: false},
    {v: 800, q: '1883, Which New York Bridge opens', a: 'Brooklyn Bridge', f:'', c: false},
    {v: 1200, q: 'Published 1830, Who had a little what?', a: 'Mary had a little lamb', f:'', c: false},
    {v: 1600, q: 'Death of which \'Polish\' \nAstronomer in 1543', a: 'Nicolaus Copernicus', f:'', c: false},
    {v: 2000, q: 'Birthdate of one of the most \nsuccessful ever folk musicians', a: 'Bob Dylan, born 1941', f:'', c: false}],
  Anagrams: [{v: 400, q: 'Viola I (Person)', a: 'Olivia', f:'', c: false},
    {v: 800, q: 'Rain Max (Work tool)', a: 'Xamarin', f:'', c: false},
    {v: 1200, q: 'Cramp End\n(Activity c.2004)', a: 'Nerd Camp', f:'', c: false},
    {v: 1600, q: 'Levelness No Rusts (Person)', a: 'Russell Stevenson', f:'', c: false},
    {v: 2000, q: 'Mattress Oats\n(Activity c.2017)', a: 'Toastmasters', f:'', c: false}],
  FamousJoshs: [{v: 400, q: 'All Blacks Flanker', a: 'Josh Kronfeld', f:'', c: false},
    {v: 800, q: 'U2 Album', a: 'The Joshua Tree', f:'', c: false},
    {v: 1200, q: 'American actor and former model', a: 'Josh Duhamel, also accept Josh Hartnett', f:'', c: false},
    {v: 1600, q: 'Queens of the Stone Age frontman', a: 'Josh Homme', f:'', c: false},
    {v: 2000, q: 'Which American writer used "Josh"\n as an early pseudonym of his Pen Name, \nhint: 10/10 moustache', a: 'Mark Twain', f:'', c: false}],
  FoodsoftheJosh: [{v: 400, q: 'Josh\'s Favourite Dessert', a: 'Lemon Meringue Pie', f:'', c: false},
    {v: 800, q: 'The secret ingredient in \nthose expensive cocktails', a: 'Gunpowder', f:'', c: false},
    {v: 1200, q: 'Josh\'s favourite coffee is \nfrom what country (2 answers)', a: 'Vietnam or Cuba', f:'', c: false},
    {v: 1600, q: 'Broke one bottle of this, and \nreceived 12 replacement bottles', a: 'Jack Daniels', f:'', c: false},
    {v: 2000, q: 'Essential Josh Flatting Food ingredient', a: 'Frozen Vegetables aka Mixies', f:'', c: false}],
  JoshPhotos: [{v: 400, q: 'Name the City', a: 'Vancouver', f:'shining.JPG', c: false},
    {v: 800, q: 'Name the annual "holiday"', a: 'Father\'s Day', f:'fathersday.JPG', c: false},
    {v: 1200, q: 'Name the Activity/Sport\n where this was taken', a: 'Archery', f:'archery.JPG', c: false},
    {v: 1600, q: 'Name the puppet thing', a: 'Bobby (I think)', f:'puppet.JPG', c: false},
    {v: 2000, q: 'Name the Boat', a: 'USS Missouri', f:'ship.JPG', c: false}]
};

export default questions;

